### ISSUE TITLE
npm requires `npm login` in github actions

### ISSUE THREAD

**Issue by phun-ky** [release-it/release-it#1042]
I have set `NPM_TOKEN` in action secrets, and I have this setup:

**publish.yml**:

```yml
# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18
      - name: Install dependencies
        run: | # Install and link dependencies
          npm i
      - name: "Release" # Interesting step
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm run release
  notify:
    name: Notify failed build
    needs: publish
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}

```

**.npmrc**:

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}

```

**.release-it.json*:

```json
{
  "git": {
    "commitMessage": "chore: 🤖 release v${version}"
  },
  "github": {
    "release": true,
    "tokenRef": "GH_TOKEN"
  },
  "npm": {
    "publish": true
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "conventionalcommits"
      },
      "infile": "CHANGELOG.md"
    }
  }
}

```

What could be the issue here?

**Comment by webpro** [comment]
What do you see? What did you try?

Are the tokens available as environment variables for release-it to pick them up?

**Comment by phun-ky** [comment]
![image](https://github.com/release-it/release-it/assets/1714029/99d2aaba-155b-4edb-944e-f00657750eb1)

I tried to use a publish workflow with github actions. I have `NPM_TOKEN` set as a repository secret

**Comment by JoshuaKGoldberg** [comment]
FWIW I've been manually running `npm config set`:
* In TypeScript-land: https://github.com/JoshuaKGoldberg/release-it-action/blob/53eb6bcdf3da0ac2bb7321d921a2fa328c5d1397/src/index.ts#L41
* Previous GitHub Actions `.yml` equivalent: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/f12451821d64b6e3ac00d0d1fdc307d4c992e162/.github/workflows/release.yml#L16-L18

@phun-ky I'm under the impression GitHub Actions require explicitly passing environment variables to actions. Example:

```yml
      - name: "Release" # Interesting step
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Just confirming, have you tried that? _(or am I wrong?)_

**Comment by AlexandreAtErgosign** [comment]
I am currently facing this issue with

```yaml
- name: Release with release-it
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm run release-it-$RELEASE_LEVEL
        env:
          RELEASE_LEVEL: ${{ github.event.inputs.version_inc }}
          GITHUB_TOKEN: ${{ secrets.GTIHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GTIHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GTIHUB_TOKEN }}
```

I get 
```
 npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://npm.pkg.github.com/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

Also note that I am trying to publish on the registry github packages.
