### ISSUE TITLE
Release-it picks up wrong release number. 

### ISSUE THREAD

**Issue by hickey** [release-it/release-it#1080]
I have been trying to make `release-it` work in a GitHub Actions workflow that basically has 3 jobs: create the release, build the package and attach the package to the release. The first two jobs are working without any issues. It is the last job that is not finding the current release and failing. 

Here is my `.release-it.yaml` configuration:

```yaml
git:
  commit: true
  commitMessage: "chore(release): ${version}"
  commitArgs: ""
  tag: true
  tagName: "v${version}"
  tagAnnotation: "Automated release: ${version}"
  push: true
  requireBranch: release-job
  requireCommits: true
  changelog: "npx auto-changelog --stdout --commit-limit false"

github:
  release: true
  releaseName: "v${version}"

npm:
  publish: false

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: Features
        - type: fix
          section: Bug Fixes
        - tyep: docs
          section: Documentation
```

Here is the jobs from the workflow:

```yaml
jobs:
  create-release:
    runs-on: ubuntu-latest
    # container:
    #   image: registry.gitlab.com/wt0f/gitlab-runner-images/node:latest
    outputs:
      build_version: ${{ steps.detect_version.outputs.build_version }}
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_IT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install -g release-it @release-it/conventional-changelog @commitlint/config-conventional @commitlint/cli auto-changelog
      - id: detect_version
        run: echo "build_version=$(npx release-it --release-version)" >> $GITHUB_OUTPUT
      - run: git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
      - run: npx release-it -VV --ci
      - run: git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
      # - run: git checkout master
      # - run: git rebase release
      # - run: git push

  build-meshchat-package:
    needs: create-release
    uses:
      ./.github/workflows/build-meshchat-package.yaml
    with:
      build_version: ${{ needs.calculate-version-number.outputs.build_version }}
      build_dir: package/meshchat-ipkg

  add-meshchat-package-to-release:
    needs: build-meshchat-package
    # container:
    #   image: registry.gitlab.com/wt0f/gitlab-runner-images/node:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm install -g release-it @release-it/conventional-changelog @commitlint/config-conventional @commitlint/cli auto-changelog
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.release_meshchat_package.outputs.package_file }}
          path: ${{ needs.release_meshchat_package.outputs.package_file }}
      - run: git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
      - run: npx release-it -VV --ci --no-increment --no-git --no-npm --github.update=true --github.assets='*.ipk'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_IT_TOKEN }}
```

I still have some of the debugging in the jobs where I have been trying to track the problem down and identify if I am causing the issue. I don't think I have made a mistake with the configuration so this is why I am now creating this issue to get further eyes on the output to see if I am mistaken. 

Here is the output from the `create-release` job (I have truncated the logs to something more appropriate to reduce size):

```
Run git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
* e98269c - (37 seconds ago) fixup (HEAD -> release-job, origin/release-job)
* d63b3be - (3 minutes ago) fixup
* d73ee89 - (4 minutes ago) fixup
* 5ad4228 - (9 minutes ago) fixup
* 1b772b7 - (45 minutes ago) fixup
* e3d6fcc - (74 minutes ago) fixup
* 409c105 - (81 minutes ago) fix: update-version.sh can now be told version to set
* 71c1f9e - (4 days ago) debug: transfer data between jobs
* 425db4a - (4 days ago) debug: set release-it to work on any branch
* 1b70a52 - (5 days ago) feat!: dummy commit to bump version
* 8f0f98b - (5 days ago) chore: add build packages to release
* f2d1b42 - (5 days ago) chore: make build-meshchat-package a reusable workflow
* 269f7cc - (5 days ago) chore: add documentation section to changelog
* bca10dc - (5 days ago) chore: create release CI job
* e3ede53 - (5 days ago) Added beginnings of package building code
* bb00a22 - (5 days ago) Initial pass at reorganization
* fabd985 - (6 days ago) fix: discover zone name from /etc/config.mesh (#36) (origin/master)
* d06ca05 - (7 days ago) chore: add release-it config file for automated releases
* 312a6bd - (7 days ago) chore: remove packages from repo
* 8ff5f6e - (7 days ago) add more fields to bug issue template
* 5e9c8f6 - (7 days ago) feat: add message class abstracting message handling (#23)
* b70bd0a - (7 days ago) fix: set epoch in send_message API even if not specified
* 08114cb - (7 days ago) Update Bug Report.yml
* 3696b24 - (7 days ago) build: Updates to better name packages
* 9fd375f - (7 days ago) chore: Added feature request issue template
* 7947b48 - (7 days ago) chore: Added Bug Report issue template
* 3ec6663 - (7 days ago) docs: Updated README with history of MeshChat
* c8be3a8 - (7 days ago) feat: Set send channel when channel filter changed
* 8155f3a - (7 days ago) Moved MeshChat source to top level
* aa479b2 - (7 days ago) Added branch name and commit ref to testing builds
* 7ddcb0e - (7 days ago) Fixed the installation of web files
* 451216f - (7 days ago) Fixed installation of cgi-bin after reorg
* f324cbf - (7 days ago) More reorganization of files
* 1550bb1 - (7 days ago) Updating version info in meshchatconfig.lua
* 8e52bd9 - (7 days ago) Removed build file as no longer needed
* 3156de7 - (7 days ago) Added build MeshChat package job
* 4dd3c9c - (7 days ago) Refactored build API workflow
* 63b0b5e - (7 days ago) Storing generated package as an artifact
* a796be3 - (7 days ago) Fixed incorrect param order for tar in ipk-build.sh
* e29f7fa - (7 days ago) Updated GitHub workflow
* 4805ed6 - (7 days ago) Fixed testing tag for version number
* b616db4 - (7 days ago) Minor fixes to populate-meshchat-api-fs.sh
* 39488ac - (7 days ago) Now making directories during package build
* ce5cecf - (7 days ago) Added beginnings of package building code
* 36a4442 - (7 days ago) Initial pass at reorganization
* f0709f6 - (7 days ago) fix: fix missing tab for file sharing
| * d5de54b - (6 days ago) fix: discover zone name from /etc/config.mesh (#36) (tag: v2.10.0, origin/release)
|/  
* 3ef31dc - (7 days ago) fix missing tab for file sharing (tag: v2.9.0, tag: v2.9)
| * c9b5157 - (6 weeks ago) move message checksum code to update() and recalc when channel changed (origin/default-channel)
===============================================================
Run npx release-it -VV --ci
$ git rev-parse --abbrev-ref HEAD
release-job
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.release-job.remote
origin
$ git remote get-url origin
https://github.com/hickey/meshchat
$ git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0
v2.9.0
$ git symbolic-ref HEAD
refs/heads/release-job
$ git for-each-ref --format="%(upstream:short)" refs/heads/release-job
origin/release-job
$ git describe --tags --match=v* --abbrev=0  [cached]
$ git rev-list v2.9.0..HEAD --count
46
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.release-job.remote  [cached]
$ git remote get-url origin  [cached]
$ git fetch  [cached]
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0  [cached]
🚀 Let's release meshchat (2.9.0...3.0.0)
Changelog:
## [3.0.0](https://github.com/hickey/meshchat/compare/v2.9.0...v3.0.0) (2024-02-12)

### ⚠ BREAKING CHANGES
* dummy commit to bump version
### Features
* add message class abstracting message handling ([#23](https://github.com/hickey/meshchat/issues/23)) ([5e9c8f6](https://github.com/hickey/meshchat/commit/5e9c8f653188462323e0dd9ef71804ac67265098))
* dummy commit to bump version ([1b70a52](https://github.com/hickey/meshchat/commit/1b70a52bdb99f6373e1687bfa99fdaa2f278d847))
* Set send channel when channel filter changed ([c8be3a8](https://github.com/hickey/meshchat/commit/c8be3a8f3ac89c5390815f88f5892ccf23fcea9f))

### Bug Fixes
* discover zone name from /etc/config.mesh ([#36](https://github.com/hickey/meshchat/issues/36)) ([fabd985](https://github.com/hickey/meshchat/commit/fabd9850210c90d5162c5f738e0e0ea167b122f3))
* fix missing tab for file sharing ([f0709f6](https://github.com/hickey/meshchat/commit/f0709f6522c27d37b950a273eeb532dacebfadfe))
* set epoch in send_message API even if not specified ([b70bd0a](https://github.com/hickey/meshchat/commit/b70bd0a41a2d36cff180630f5a61758fb1f266d3))
* update-version.sh can now be told version to set ([409c105](https://github.com/hickey/meshchat/commit/409c105060fd2ada184736f49831195917f06743))
$ Writing changelog to CHANGELOG.md
$ git add CHANGELOG.md
$ git status --short --untracked-files=no
A  CHANGELOG.md
Changeset:
A  CHANGELOG.md
$ git add . --update

$ git commit --message chore(release): 3.0.0
[release-job 7fecbef] chore(release): 3.0.0
 1 file changed, 22 insertions(+)
 create mode 100644 CHANGELOG.md
$ git tag --annotate --message Automated release: 3.0.0 v3.0.0

$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/release-job  [cached]
$ git push --follow-tags
! octokit repos.createRelease "v3.0.0" (v3.0.0)
octokit repos.createRelease: done (https://api.github.com/repos/hickey/meshchat/releases/141668770)
🔗 https://github.com/hickey/meshchat/releases/tag/v3.0.0
🏁 Done (in 2s.)
===============================================================
Run git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
* 7fecbef - (1 second ago) chore(release): 3.0.0 (HEAD -> release-job, tag: v3.0.0, origin/release-job)
* e98269c - (39 seconds ago) fixup
* d63b3be - (3 minutes ago) fixup
* d73ee89 - (4 minutes ago) fixup
* 5ad4228 - (9 minutes ago) fixup
* 1b772b7 - (45 minutes ago) fixup
* e3d6fcc - (74 minutes ago) fixup
* 409c105 - (81 minutes ago) fix: update-version.sh can now be told version to set
* 71c1f9e - (4 days ago) debug: transfer data between jobs
* 425db4a - (4 days ago) debug: set release-it to work on any branch
* 1b70a52 - (5 days ago) feat!: dummy commit to bump version
* 8f0f98b - (5 days ago) chore: add build packages to release
```
That all looks good and what I would expect. The release gets calculated to be `v3.0.0` and creates the GitHub release using this version. In the last `git log` you can see the commit with the `v3.0.0` tag. 

Now in the last job, this is where things seem to go sideways. Here is the output (again truncating the log).

```
Run git log --graph --all --pretty=format:'%h - (%cr) %s%d' --abbrev-commit --date=relative
* 7fecbef - (43 seconds ago) chore(release): 3.0.0 (tag: v3.0.0)
* e98269c - (81 seconds ago) fixup (HEAD -> release-job, origin/release-job)
* d63b3be - (3 minutes ago) fixup
* d73ee89 - (5 minutes ago) fixup
* 5ad4228 - (10 minutes ago) fixup
* 1b772b7 - (46 minutes ago) fixup
* e3d6fcc - (75 minutes ago) fixup
* 409c105 - (82 minutes ago) fix: update-version.sh can now be told version to set
* 71c1f9e - (4 days ago) debug: transfer data between jobs
* 425db4a - (4 days ago) debug: set release-it to work on any branch
* 1b70a52 - (5 days ago) feat!: dummy commit to bump version
* 8f0f98b - (5 days ago) chore: add build packages to release
* f2d1b42 - (5 days ago) chore: make build-meshchat-package a reusable workflow
* 269f7cc - (5 days ago) chore: add documentation section to changelog
* bca10dc - (5 days ago) chore: create release CI job
* e3ede53 - (5 days ago) Added beginnings of package building code
* bb00a22 - (5 days ago) Initial pass at reorganization
* fabd985 - (6 days ago) fix: discover zone name from /etc/config.mesh (#36) (origin/master)
* d06ca05 - (7 days ago) chore: add release-it config file for automated releases
* 312a6bd - (7 days ago) chore: remove packages from repo
* 8ff5f6e - (7 days ago) add more fields to bug issue template
* 5e9c8f6 - (7 days ago) feat: add message class abstracting message handling (#23)
* b70bd0a - (7 days ago) fix: set epoch in send_message API even if not specified
* 08114cb - (7 days ago) Update Bug Report.yml
* 3696b24 - (7 days ago) build: Updates to better name packages
* 9fd375f - (7 days ago) chore: Added feature request issue template
* 7947b48 - (7 days ago) chore: Added Bug Report issue template
* 3ec6663 - (7 days ago) docs: Updated README with history of MeshChat
* c8be3a8 - (7 days ago) feat: Set send channel when channel filter changed
* 8155f3a - (7 days ago) Moved MeshChat source to top level
* aa479b2 - (7 days ago) Added branch name and commit ref to testing builds
* 7ddcb0e - (7 days ago) Fixed the installation of web files
* 451216f - (7 days ago) Fixed installation of cgi-bin after reorg
* f324cbf - (7 days ago) More reorganization of files
* 1550bb1 - (7 days ago) Updating version info in meshchatconfig.lua
* 8e52bd9 - (7 days ago) Removed build file as no longer needed
* 3156de7 - (7 days ago) Added build MeshChat package job
* 4dd3c9c - (7 days ago) Refactored build API workflow
* 63b0b5e - (7 days ago) Storing generated package as an artifact
* a796be3 - (7 days ago) Fixed incorrect param order for tar in ipk-build.sh
* e29f7fa - (7 days ago) Updated GitHub workflow
* 4805ed6 - (7 days ago) Fixed testing tag for version number
* b616db4 - (7 days ago) Minor fixes to populate-meshchat-api-fs.sh
* 39488ac - (7 days ago) Now making directories during package build
* ce5cecf - (7 days ago) Added beginnings of package building code
* 36a4442 - (7 days ago) Initial pass at reorganization
* f0709f6 - (7 days ago) fix: fix missing tab for file sharing
| * d5de54b - (6 days ago) fix: discover zone name from /etc/config.mesh (#36) (tag: v2.10.0, origin/release)
|/  
* 3ef31dc - (7 days ago) fix missing tab for file sharing (tag: v2.9.0, tag: v2.9)
| * c9b5157 - (6 weeks ago) move message checksum code to update() and recalc when channel changed (origin/default-channel)
| * c575379 - (6 weeks ago) set default channel upon initialization
===============================================================
Run npx release-it -VV --ci --no-increment --no-git --no-npm --github.update=true --github.assets='*.ipk'
$ git rev-parse --abbrev-ref HEAD
release-job
$ git config --get branch.release-job.remote
origin
$ git remote get-url origin
https://github.com/hickey/meshchat
$ git fetch
From https://github.com/hickey/meshchat
   e98269c..7fecbef  release-job -> origin/release-job
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0
v2.9.0
$ git rev-list v2.9.0 --tags --max-count=1
7fecbef5d9b3759dd4aba5da30ba7112223e3aef
$ git describe --tags --abbrev=0 "7fecbef5d9b3759dd4aba5da30ba7112223e3aef^"
v2.9.0
WARNING GitHub release for tag v2.9.0 was not found. Creating new release.
$ git log --pretty=format:"* %s (%h)" v2.9.0...v2.9.0^1
* fix missing tab for file sharing (3ef31dc)
🚀 Let's update meshchat (currently at 2.9.0)
Changelog:
* fix missing tab for file sharing (3ef31dc)
$ Writing changelog to CHANGELOG.md
$ git add CHANGELOG.md
! octokit repos.createRelease "v2.9.0" (v2.9.0)

ERROR 422 (Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"} - https://docs.github.com/rest/releases/releases#create-a-release)
Error: Process completed with exit code 1.
```

I am unable to determine why `v2.9.0` continues to be identified as the last release.
