### ISSUE TITLE
Release It not creating release on github when npm.publish is true

### ISSUE THREAD

**Issue by suparthghimire** [release-it/release-it#1144]
**Description**
I have a npm library that needs to be published to npm and a github release must be created. I have added my .releaserc and .github/workflows/create_release.yml code below. The action runs when pushed to main, however after creating a npm publish, release on github is not created. Additionally, CHANGELOG.md is also not updated

.releaseitrc
```json
{
  "$schema": "https://unpkg.com/release-it@17/schema/release-it.json",
  "git": {
    "commitMessage": "chore: release v${version}"
  },
  "github": {
    "release": true
  },
  "npm": {
    "publish": true
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fix"
          }
        ]
      }
    }
  }
}
```

.github/workflows/create_release.yml
```yml
name: Publish to NPM

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

        # setup node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      # Pnpm stuff
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # build
      - name: build
        run: pnpm run build

      - name: Set Git Credentials
        run: |
          git config user.name "${GITHUB_ACTOR}" 
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release It 🚀
        run: pnpm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Action Screenshot
![image](https://github.com/user-attachments/assets/709abe46-08f0-4df1-9927-9a5ca4393a2e)

Latest Release on GitHub
![image](https://github.com/user-attachments/assets/a7de7cc9-f917-4699-bb02-c5d461d480c7)

Latest Release on NPM
![Screenshot from 2024-09-10 19-17-36](https://github.com/user-attachments/assets/566b2380-5683-4baf-bace-bba875b492f5)

The commit for which this action ran:
`fix: release it test`
