### ISSUE TITLE
Error: Permission Denied with `release-it` Using GitHub Actions

### ISSUE THREAD

**Issue by AtelyPham** [release-it/release-it#1157]
Hello,

I am experiencing an issue when using `release-it` to automate my release process through GitHub Actions. The workflow fails with the following error:

```
✔ Git tag
- Git push
Rolling back remote tag push @atelypham/tangle-substrate-types/v0.6.1
WARNING An error was encountered when trying to rollback the tag on the remote: fatal: could not read Username for 'https://github.com': No such device or address
✖ Git push
ERROR git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Rolling back changes...
Deleting local tag @atelypham/tangle-substrate-types/v0.6.1
Resetting local changes made
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

### Config, Workflow and Logs

- **Config File**: [.release-it.ts](https://github.com/AtelyPham/tangle/blob/main/types/.release-it.ts).
- **Workflow File**: [View Workflow](https://github.com/AtelyPham/tangle/actions/runs/11130728513/workflow).
- **Action Log**: [View Logs](https://github.com/AtelyPham/tangle/actions/runs/11130728513/job/30930739442).

**Comment by webpro** [comment]
> WARNING An error was encountered when trying to rollback the tag on the remote: fatal: could not read Username for 'https://github.com': No such device or address
> ✖ Git push
> ERROR git@github.com: Permission denied (publickey).


This doesn't seem right? Is access set up properly, and are all the environment variables set properly?

**Comment by AtelyPham** [comment]
This is the configuration for the personal access token.

![CleanShot 2024-10-04 at 16 58 11@2x](https://github.com/user-attachments/assets/2d3867a5-91d8-422a-9eef-f6f4aa737be1)

For the `GITHUB_TOKEN` environment variable, I’ve tested both my personal access token and the auto-generated GitHub token, but both resulted in the same error:

```shell
ERROR git@github.com: Permission denied (publickey).
```
<details><summary>You can see my Github workflow file here:</summary>
<p>

```yaml
name: Publish Types

# If changes are made to the types/src/** files
# Issue a new release to npm for the types package.
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'types/src/**'
      - 'types/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: cd types && yarn install

      - name: Configure Github Actions user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish the package
        run: cd types && yarn publish-types --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Using Github auto-generated token
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Using personal access token
          GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}

```

</p>
</details>

**Comment by webpro** [comment]
I don't see an obvious mistake here. Looks like an access issue with a public key. Have you got `RELEASE_IT_GITHUB_TOKEN` vs `GITHUB_TOKEN` right?

Also, sorry, I can't go out and debug individual cases (I would expect more issue reports if something's wrong with release-it itself).

**Comment by webpro** [comment]
Isn't this `secrets.GITHUB_TOKEN`?

<img width="408" alt="Screenshot 2024-10-04 at 12 25 30 PM" src="https://github.com/user-attachments/assets/cc7368ef-27ac-474f-99d4-35552b8feeb1">

**Comment by AtelyPham** [comment]
> I don't see an obvious mistake here. Looks like an access issue with a public key. Have you got `RELEASE_IT_GITHUB_TOKEN` vs `GITHUB_TOKEN` right?
> 
> Also, sorry, I can't go out and debug individual cases (I would expect more issue reports if something's wrong with release-it itself).

What is the public key for this case? 

I can run the release locally with `release-it` using the same PAT and NPM token; I believe my error is due to a misconfiguration on GitHub.

**Comment by webpro** [comment]
The public key is for ssh+git protocol to push commits and tags to Git origin.

The token (`GITHUB_TOKEN`) is for creating a GitHub Release with the GH API.

**Comment by AtelyPham** [comment]
Could you explain how to set up, check, or enable the ssh+git protocol public key, or is this managed by GitHub?

**Comment by webpro** [comment]
For the Git part (commit/push/tag), it's mostly just executing (git) commands. Git itself handles the rest. For the GitHub release it picks up the `GITHUB_TOKEN` environment variable to talk to the GitHub API. So, yeah.

**Comment by AtelyPham** [comment]
I resolved this issue by incorporating the [`ssh-agent`](https://github.com/webfactory/ssh-agent/tree/v0.5.4/?tab=readme-ov-file#usage) into my release workflow. I generated an SSH keypair, set the public key as the [deploy key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#set-up-deploy-keys) for the repository, and used the private key with the [`ssh-agent`](https://github.com/webfactory/ssh-agent/tree/v0.5.4/?tab=readme-ov-file#usage) action.

Here are the lines I added to my workflow to resolve the issue (note that I set up my SSH key prior to this):

```yaml
# Checkout, setup-node actions...

# Configure SSH with private SSH key
- name: Attach SSH key
  uses: webfactory/ssh-agent@v0.5.4
  with:
    ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

# Configure git user, npm config, install deps, and run release 🚀
```
