### ISSUE TITLE
Github actions CI - PUT 404 not found for registry

### ISSUE THREAD

**Issue by alvarosabu** [release-it/release-it#1213]
Hi, I'm trying to set up a GitHub action to release automatically, but it gives me this error https://github.com/alvarosabu/core-pkg-test/actions/runs/14269283612/job/39998752948

```
> release-it --ci --verbose
$ pnpm run lint
> @alvarosabu/core-pkg-test@1.1.0 lint /home/runner/work/core-pkg-test/core-pkg-test
> oxlint .
Found 0 warnings and 0 errors.
Finished in 2ms on 7 files with 99 rules using 4 threads.
🚀 Let's release @alvarosabu/core-pkg-test (1.1.0...1.1.1)
Changelog:
## [1.1.1](https://github.com/alvarosabu/core-pkg-test/compare/v1.1.0...v1.1.1) (2025-04-04)
$ pnpm build
> @alvarosabu/core-pkg-test@1.1.1 build /home/runner/work/core-pkg-test/core-pkg-test
> rolldown -c rolldown.config.ts
[log] <DIR>/index.js.map  asset │ size: 4.21 kB
[log] <DIR>/index.js      chunk │ size: 1.28 kB
[log]
[success] Finished in 17.54 ms
Changeset:
 M CHANGELOG.md
 M package.json
ERROR npm notice
npm notice 📦  @alvarosabu/core-pkg-test@1.1.1
npm notice Tarball Contents
npm notice 888B README.md
npm notice 1.3kB dist/index.js
npm notice 4.2kB dist/index.js.map
npm notice 1.2kB package.json
npm notice Tarball Details
npm notice name: @alvarosabu/core-pkg-test
npm notice version: 1.1.1
npm notice filename: alvarosabu-core-pkg-test-1.1.1.tgz
npm notice package size: 2.6 kB
npm notice unpacked size: 7.6 kB
npm notice total files: 4
npm notice
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm error code E404
npm error 404 Not Found - PUT https://registry.npmjs.org/@alvarosabu%2fcore-pkg-test - Not found
npm error 404
npm error 404  '@alvarosabu/core-pkg-test@1.1.1' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-04-04T[16](https://github.com/alvarosabu/core-pkg-test/actions/runs/14269283612/job/39998752948#step:8:17)_00_09_512Z-debug-0.log
Rolling back changes...
Resetting local changes made
 ELIFECYCLE  Command failed with exit code 1.
```

Weird thing is that https://registry.npmjs.org/@alvarosabu%2fcore-pkg-test does exist

Same command works fine locally, same `NPM_TOKEN` locally and on the repo secrets. I'm quite stuck, not sure how to fix it.

## Additional info

My [release-it.json](https://github.com/alvarosabu/core-pkg-test/blob/main/.release-it.json)

```ts
{
  "$schema": "https://unpkg.com/release-it@18/schema/release-it.json",
  "git": {
    "commitMessage": "chore: release v${version}",
    "tagName": "v${version}"
  },
  "github": {
    "release": true,
    "releaseName": "v${version}"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "conventionalcommits",
      "infile": "CHANGELOG.md"
    }
  },
  "npm": {
    "publish": true,
    "skipChecks": true
  },
  "hooks": {
    "before:init": ["pnpm run lint"],
    "after:bump": "pnpm build",
    "after:git:release": "echo After git push, before github release",
    "after:release": "echo Successfully released ${name} v${version} to ${repo.repository}."
  }
}
```

My [.github/workflow/release.yml](https://github.com/alvarosabu/core-pkg-test/blob/main/.github/workflows/release.yml)

```
name: Release CI

on:
  push:
    branches: [main, next, beta]

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1 # Skip installing simple-git-hooks

jobs:
  release:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release --ci --verbose
```

I appreciate the help 🙏🏻
