### ISSUE TITLE
tinyexec and lefthook issues, git commit hangs

### ISSUE THREAD

**Issue by efstathiosntonas** [release-it/release-it#1226]
Hi, after upgrading to `19.0.2` the `git commit --message chore: blablalba` hangs with no error. 

I believe the issue started because `execa` was replaced by `tinyexec`. 

It's hard to debug (even with `-VV`) what is causing the issue.

If I run `lefthook run pre-commit` or if i manually `git commit ....` everything works fine. 

If i pass --no-verify `const commitMessageArgs = msg ? ['--message', msg, '--no-verify'] : ['--no-verify'];` then it proceeds to the commit. 

If i change the shell `execWithArguments` to:

```js
import { spawn } from 'node:child_process';

async execWithArguments(command, options = {}, { isExternal }) {
    const [program, ...programArgs] = command;

    return new Promise((resolve, reject) => {
      const proc = spawn(program, programArgs, {
        stdio: 'inherit', // Inherit stdio from the parent process
        shell: true,      // Use shell if needed
      });

      proc.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`Process exited with code ${code}`));
        }
      });

      proc.on('error', (err) => {
        reject(err);
      });
    });
  }
 ```

and replace `commitMessageArgs` at `Git.js` with:

```js
const commitMessageArgs = msg ? ['--message', `"${msg}"`] : [];
```

and on same file on the `tag` function: 
```js
return this.exec(['git', 'tag', '--annotate', '--message', `"${message}"`, ...fixArgs(args), tagName])
```

then it commits fine. In other words, when using node's spawn instead of tinyexec it woks as it should.

`lefthook`

```yaml
no_tty: true
pre-commit:
  piped: true
  commands:
    1_depcruiser:
      run: ./node_modules/.bin/depcruise src
    2_prettier:
      glob: "*.{js,json,md,ts,tsx,graphql}"
      run: ./node_modules/.bin/prettier --write {staged_files}
    3_oxlint:
      run: ./node_modules/.bin/oxlint
    4_lint:
      glob: "*.{js,ts,jsx,tsx}"
      run: ./node_modules/.bin/eslint --no-interactive {staged_files}
    5_types:
      glob: "*.{js,ts,jsx,tsx}"
      run: ./node_modules/.bin/tsc --noEmit
      #run: tsc-files-ignore-imports --noEmit --pretty $(git diff --staged --name-only)

commit-msg:
  parallel: true
  commands:
    commitlint:
      run: ./node_modules/.bin/commitlint --edit $1
post-commit:
  parallel: true
  commands:
    updateVersion:
      run: yarn updateVersion
```

Let me know if you want any other info.

edit: smells like `TTY` issue, I think tinyexec does not handle it like `execa` does. In the spawn above we `stdio: 'inherit'` and I believe it does the trick.
