### ISSUE TITLE
Travis CI: "ERROR Not authenticated with npm. Please `npm login` and try again."

### ISSUE THREAD

**Issue by thezimmee** [release-it/release-it#499]
I'm trying to run release-it on Travis CI, and getting the error in the title. I have `NPM_TOKEN` defined in Travis CI, I just am not sure how release-it and Travis CI are supposed to interact together.

Here is my `.release-it.json`:

```json
{
  "increment": "conventional:angular",
  "scripts": {
    "changelog": "npx conventional-changelog -p angular -u | tail -n +3",
    "beforeStage": "npx conventional-changelog -p angular -i CHANGELOG.md -s"
  },
  "git": {
    "commit": false,
    "requireCleanWorkingDir": false,
    "requireUpstream": false
  },
  "github": {
    "release": true
  },
  "npm": {
    "release": true,
    "tag": "next",
    "assets": ["examples", "esm", "umd", "README.md"]
  }
}
```

Here is my `.travis.yml`:

```yml
language: node_js
node_js: "9"

cache:
  bundler: true

notifications:
  email:
    on_failure: always

env: NODE_ENV=test

# Publish to NPM only.
before_script: npm prune -d
script: npm test -d

# release-it to NPM and GitHub.
deploy:
  provider: script
  email: thezimmee@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  script:
    - npm run release -- -n --verbose

# Publish to NPM only.
branches:
  only:
    - master
    - /^greenkeeper/.*$/
```

Here is my Travis CI log if it's helpful: https://api.travis-ci.org/v3/job/515392876/log.txt

I apologize, I'm sure I'm not configuring Travis correctly. I've searched for answers but can't find anything that seems relevant. Do you mind pointing me in the right direction?

**Comment by webpro** [comment]
A couple of remarks:

* I think it's useful to make sure things work locally first.
* `npm.release` should be `npm.publish`
* The `npm.assets` option does nothing (`assets` are only relevant for `github` or `gitlab`).
* The `-n` flag for release-it should not be necessary within CI environments.
* release-it delegates to `npm publish`; from here, also see [npm Releasing - Travis CI](https://docs.travis-ci.com/user/deployment/npm/)

Let me know if you still have any issues!

**Comment by thezimmee** [comment]
Thank you much for the help @webpro. Sorry for the silly mistakes. I modified the `.release-it.json` configuration based on your feedback and am still getting the same error.

> I think it's useful to make sure things work locally first.

Are you saying to test release-it locally? Or Travis locally? I did do a dry run of release-it locally before I pushed to Travis, it succeeds on both github and npm. I have never worked with Travis locally though, if that's what your suggesting (seems like that would add another layer of complexity to local development)...?

> release-it delegates to npm publish; from here, also see npm Releasing - Travis CI

I think this is where I'm confused... Here is what my `.travis.yml` looked like before I added release-it:

```yml
before_script: npm prune -d
script: npm test -d

deploy:
   provider: npm
   email: thezimmee@gmail.com
   api_key: $NPM_TOKEN
   skip_cleanup: true
```

If the main `script` (`npm test`) ran successfully, it would successfully publish to NPM. It sounds like you're saying this is how I need to configure my NPM deploy. Yes? I can do that... however, then where do I add release-it? Is it part of the `deploy` step? Part of the main `script`? Somewhere else?

Or maybe you're saying something different. In any case, I'm still getting the same error (`ERROR Not authenticated with npm. Please `npm login` and try again.`).

Do you mind providing some further clarification and guidance? If you can provide a sample `.travis.yml` to show me how Travis should interact with release-it, that would be very helpful to...

For the record, here is what my `.travis.yml` looks like now:

```yml
before_script: npm prune -d
script: npm test -d

# release-it to NPM and GitHub.
deploy:
  provider: script
  email: thezimmee@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  script:
    - npm run release
```

And here is the raw Travis log: https://api.travis-ci.org/v3/job/516273920/log.txt
