### ISSUE TITLE
npm publish from CI

### ISSUE THREAD

**Issue by jeetiss** [release-it/release-it#543]
I am trying to automate the publication to the NPM and I have the following problem

- I already have `.npmrc` file in the repository

- following script changes it
`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`

- release [fails](https://travis-ci.com/jeetiss/tabs/jobs/222203183) with `ERROR Working dir must be clean.`

I can remove and add to gitignore `.npmrc` file, but I think it's not the best solution, maybe you can help me

#### travis config

```
language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm test
        - npm run size
    - stage: release
      script:
        - npm run build
        - npm run release -- --ci

stages:
  - test
  - name: release
    if: |
      branch = master AND \
      type = push AND \
      commit_message !~ /(no-release)/
```

#### release-it config
```
"release-it": {
    "github": {
      "release": true
    },
    "git": {
      "commitMessage": "chore: release ${version}"
    },
    "plugins": {
      "@release-it/conventional-changelog": {
        "preset": "angular",
        "infile": "changelog.md"
      }
    }
  },
```

[repo with this stuff](https://github.com/jeetiss/tabs/)

**Comment by webpro** [comment]
You could move the travis script to a release-it hook, so this file is changed after the Git push, but before the npm publish. E.g.:

```
"release-it": {
  "hooks": {
    "before:npm:release": "echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > .npmrc"
  }
}
```

Would be nice if `git add` would have an ignore option, so we could customize which files are staged. Currently it's `--update` (default) or `--all` (with `git.addUntrackedFiles`). Not sure yet how to properly solve this.

**Comment by jeetiss** [comment]
this solution not working because login to npm required before release stage 😕

release-it fails with
```
ERROR Not authenticated with npm. Please `npm login` and try again.
```

and don't run hooks 😕

https://travis-ci.com/jeetiss/try-release-it/jobs/222372012

**Comment by webpro** [comment]
Ah, yes. Then I guess we need to make sure we can configure which files exactly are staged with Git. For example:

```
"release-it": {
    "git": {
      "requireCleanWorkingDir": false,
      "addFiles": ["package.json", "CHANGELOG.md"],
      "commitMessage": "chore: release ${version}",
    }
  }
}
```

I'd need to add something like this `git.addFiles` option in a next release. What do you think?

**Comment by yousifalraheem** [comment]
I'm not sure if this is helpful for your case but I think you should take a look at this git command:

```cmd
git update-index --assume-unchanged .npmrc
```

This command will ignore the changes to .npmrc temporarily. You can only do this if the file have been committed before and you can undo it like this
```cmd
git update-index --no-assume-unchanged .npmrc
```

**Comment by jeetiss** [comment]
@yousifalraheem thanks ❤️, that exactly what I need

**Comment by jeetiss** [comment]
I finally setup all features together, but while release release-it push new commits in master thats triggers new releases 🙌🏻

Infinity release loop, lol

<img width="956" alt="Снимок экрана 2019-08-07 в 10 40 47" src="https://user-images.githubusercontent.com/6726016/62604241-4a590f80-b900-11e9-8c8b-384326554db5.png">

**Comment by jeetiss** [comment]
WOW 🎉
i fix it, now i can publish new packages from travis, thanks @webpro 🙌🏻

in the end, have thats:

- `.travis.yml`

```
language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node

jobs:
  include:
    - stage: release
      script:
        - git checkout master
        - git remote rm origin
        - git remote add origin https://jeetiss:${GITHUB_TOKEN}@github.com/jeetiss/try-release-it.git
        - git fetch
        - git branch -u origin/master
        - git update-index --assume-unchanged .npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm run release -- --ci

stages:
  - name: release
    if: "branch = master AND type = push AND commit_message !~ /(no-release|chore: release)/"
```

- `release-it` config
```
{
    "git": {
      "commitMessage": "chore: release ${version}"
    },
    "github": {
      "release": true
    },
    "npm": {
      "publish": true
    },
    "plugins": {
      "@release-it/conventional-changelog": {
        "preset": "angular",
        "infile": "CHANGELOG.md"
      }
    }
  }
```

https://travis-ci.com/jeetiss/try-release-it/builds/122233023
