### ISSUE TITLE
GitHub Actions - Could not authenticate with GitHub using environment variable "GITHUB_TOKEN"

### ISSUE THREAD

**Issue by wfortin** [release-it/release-it#618]
I'm getting error `Could not authenticate with GitHub using environment variable "GITHUB_TOKEN"` when running `release-it` on GitHub Actions.

The GitHub API returns: `Resource not accessible by integration`, because the GitHub integrations tries to fetch the user related to the token, in GitHub actions, the token provided is not associated to any users, so there's a few options in order to support GH Actions with release-it:
- allow to skip this validation
- find other ways to validate that the token is valid
- ??

Action being run is
```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: New version detected, release package
        run: |
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

In the mean time I'll need to use a "personal token" but I'd prefer to use the GITHUB_TOKEN provided by GH actions which would make the releases published by `github-actions` instead of `wfortin`

Expected:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/2165256/76619865-29a70700-652c-11ea-938e-061397893963.png">

But right now with personal token, it gives this:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2165256/76619902-3e839a80-652c-11ea-9be0-f23d5e7d70d1.png">
