### ISSUE TITLE
GitLab-CI Integration

### ISSUE THREAD

**Issue by lucbas** [release-it/release-it#642]
Hi all

I'm trying to set up release-it with GitLab CI with the following config:

.release-it.json:
```
{
  "gitlab": {
    "release": true
  },
  "npm": {
    "publish": false
  }
}
```

.gitlab-ci.yml
```
image: docker:19.03.8

stages:
- release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  
services:
  - docker:19.03.8-dind

before_script:
  - docker info
  - ls /certs/**

release-gitlab-alpha:
  stage: release
  image: node:12.16.1-alpine
  before_script:
    - apk add --no-cache git
    - git pull origin alpha
    - npm install
  script:
    - npx release-it --preRelease=alpha --ci
  only:
    refs:
      - alpha

release-gitlab-beta:
  stage: release
  image: node:12.16.1-alpine
  before_script:
    - apk add --no-cache git
    - git pull origin beta
    - npm install
  script:
    - npx release-it --preRelease=beta --ci
  only:
    refs:
      - beta

release-gitlab-production:
  stage: release
  image: node:12.16.1-alpine
  before_script:
    - apk add --no-cache git
    - git pull origin production
    - npm install
  script:
    - npx release-it --ci
  only:
      refs:
        - production
```

I have added the GITLAB_TOKEN env to the environment variables in the Gitlab settings.

Here is the output of the pipeline with the above config:
https://gitlab.com/Lucky-JobDone/example-project/-/jobs/514594951
`ERROR fatal: ref HEAD is not a symbolic ref`

I tried to add the following code to the pipeline:
```
git remote rm origin
git remote add origin $CI_REPOSITORY_URL
git symbolic-ref HEAD refs/heads/alpha
```

The output differs, but still fails:
https://gitlab.com/Lucky-JobDone/example-project/-/jobs/514583767
`ERROR fatal: your current branch 'alpha' does not have any commits yet`

**Comment by veenarm** [comment]
Hey mate, the original checkouts are headless.
We had to do this.
```
- git checkout $CI_BUILD_REF_NAME
- git remote set-url origin "<gitusername>@gitlab.domain.com:$CI_PROJECT_PATH.git
```

This then worked for us, the reason we had to rebind the origin to SSH not HTTPS is due to https not working for us as our creds are all ssh based, but for your error I believe you just need to checkout your branch first.

**Comment by rhernand3z** [comment]
Hi @veenarm,

would you be able to provide the full script block you used in Gitlab prior to executing `release-it`? I tried the above suggestion and it still fails for me. In my scenario, it's the first time I am executing a release, so there are no prior Gitlab releases or tags. Thanks for help!

**Comment by veenarm** [comment]
We have our original npm install done in a earlier job and then cache the node_modules across the jobs.

```
  script:
    - git checkout $CI_BUILD_REF_NAME
    - git remote set-url origin "gitlab-git@gitlab.csda.gov.au:$CI_PROJECT_PATH.git"
    - patchScope=$(node convention-bump.js)
    - echo "Convention Bump = $patchScope"
    - ./node_modules/release-it/bin/release-it.js $patchScope --ci
```

the convention-bump.js just gets what we want the next version to be 'major', 'minor', 'patch' and passes it into the release-it ..

We have yaml `.release-it.yml` in the project root

```yml

npm:
  publish: false

gitlab:
  release: true

git:
  commitMessage: "[Release-it] ${version}"

```
