### ISSUE TITLE
Release-it with with 2 protected prerelease branches and 1 release branch

### ISSUE THREAD

**Issue by lucbas** [release-it/release-it#645]
Hi all

I try to set up release-it so that we can create releases based on merging into our prerelease and release branches.

Branches:
- production (release to prod environment)
- beta (prerelease to beta environment)
- alpha (prerelease to alpha environment)

The desired branching model is:

1. developers create a `feat/xyz` branch from `alpha` (alpha acts as the master branch in that sense).
2. afterwards, they merge the `feat/xyz` branch into `alpha`, test.
3. merge `alpha` into `beta`, test.
4. `beta` into `production`

This means that the changes are only pushed into one direction:
- feat/xyz -> alpha -> beta -> production.

While I was able to correctly set up release-it, it seems that the versioning is not functioning as desired, as you can see on [the releases or tag pages.](https://gitlab.com/Lucky-JobDone/example-project-2/-/tags)

As an example, I created some test runs and I run into the following issues:

- After releasing 0.0.2 (production) and creating a new feat/xyz branch that is merged into alpha, the alpha is named "0.0.2-alpha.1". I would expect it to be named 0.0.3-alpha.0: https://gitlab.com/Lucky-JobDone/example-project-2/-/tags
- I also got an error that the tag already exists in one of the test runs while merging from alpha into beta: https://gitlab.com/Lucky-JobDone/example-project-2/-/jobs/517600574

The repo is added over ssh in the pipeline and checked out properly before executing release-it.

Not sure, but a possible issue source could be that the tags/releases in the other branches (beta and production) are ahead and I somehow need to configure that release-it also checks the other branches to determine the version number.

release-it.json:
```
{
  "gitlab": {
    "release": true
  },
  "git": {
    "commit": false
  },
  "npm": {
    "publish": false,
    "ignoreVersion": true
  }
}
```

gitlab-ci.yml (shortened)
```
release-gitlab-alpha:
  stage: release
  script:
    - npx release-it --preRelease=alpha --ci
  only:
    refs:
      - alpha

release-gitlab-beta:
  stage: release
  script:
    - npx release-it --preRelease=beta --ci
  only:
    refs:
      - beta

release-gitlab-production:
  stage: release
  script:
    - npx release-it --ci
  only:
      refs:
        - production
```

I would highly, highly appreciate help on this issue! If there are ideas on how to solve this, change of the branching strategy, I'm all ears. The only requirement is just that there are 3 release branches that deploy into our 3 environments.

Edit: Added details

**Comment by webpro** [comment]
The latest tag need to be "reachable" for Git from the current commit. To get the latest tag, release-it executes this:

```
git describe --tags --abbrev=0
```

I think the issue is that the tag is set upstream, but not pulled into the repo where the release is done.

The following are commands that should not be done by release-it (at least not by default), as it changes the local state of the repo. You might want to try each of these as part of the release script, or add them as the `hooks.before:init` hook.

```
git pull
git fetch --tags
```

Sorry, don't have the time to test things here at the moment.

**Comment by lucbas** [comment]
Hi @webpro 

Thanks for your answer, I have been doing some testing and currently, the setup looks like this:

gitlab-ci.yml (alpha branch)

```yml
  before_script:
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url origin "git@gitlab.com:$CI_PROJECT_PATH.git"
    - git pull origin $CI_COMMIT_REF_NAME
    - git fetch --tags
    - npm install
  script:
    - npx release-it --preRelease=alpha --ci -VV
  only:
    refs:
      - alpha
```

release-it.json

```json
{
  "hooks": {
    "after:release": "echo Successfully released ${name} v${version} to ${repo.repository}."
  },
  "gitlab": {
    "release": true
  },
  "git": {
    "commitMessage": "chore(release): v${version} release",
    "pushArgs": ["-o ci.skip"]
  },
  "npm": {
    "publish": false,
    "ignoreVersion": true
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```


THe docs say:

> Pre-releases work in tandem with recommended bumps.

Does this mean the `@release-it/conventional-changelog` is required with prereleases? If yes, is the release version still determined by the git tags?

Further, I run into the following error:

```
! gitlab releases#createRelease "Release 1.0.1-alpha.0" (1.0.1-alpha.0)
ERROR Response code 422 (Unprocessable Entity)
Rolling back changes...
git tag --delete 1.0.1-alpha.0
git reset --hard HEAD~1
```
Full log is here: https://gitlab.com/Lucky-JobDone/example-project-3/-/jobs/522087202

I was also digging through: https://github.com/release-it/release-it/issues/533 but was not able to find a solution.

_Smaller note: While it rolls back the changes locally, the new commit is already in the repo. So maybe that needs to be rolled back too? But that would come with other caveats I suppose._
