### ISSUE TITLE
NPM_Token not working in CircleCI

### ISSUE THREAD

**Issue by gaoljie** [release-it/release-it#703]
When I run release-it cli after NPM_Token is exported, it was returning error

```yml
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12.0.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
          key: module-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths: .

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: git push --set-upstream origin master
      - run: |
          git config user.email "xx@gmail.com"
          git config user.name "xx"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: release-it --ci
      - run: yarn build
      - run: |
          yarn add gh-pages -D
          ./node_modules/.bin/gh-pages -d .docz/dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              only:
                - master
```

```json
{
  "github": {
    "release": true,
    "releaseName": "v${version}"
  },
  "git": {
    "tagName": "v${version}",
    "commitMessage": "Release v${version} [ci skip]"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```

this issue will disappear if I run `npm publish` instead

```yml
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12.0.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
          key: module-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths: .

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: git push --set-upstream origin master
      - run: |
          git config user.email "xx@gmail.com"
          git config user.name "xx"
          release-it --ci

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish
      - run: yarn build
      - run: |
          yarn add gh-pages -D
          ./node_modules/.bin/gh-pages -d .docz/dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
```

```json
{
  "npm": {
    "publish": false
  },
  "github": {
    "release": true,
    "releaseName": "v${version}"
  },
  "git": {
    "tagName": "v${version}",
    "commitMessage": "Release v${version} [ci skip]"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}

```

but the similar config seems working in other CI environment like TravisCI
```
language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node

jobs:
  include:
    - stage: release
      script:
        - git checkout master
        - git remote rm origin
        - git remote add origin https://jeetiss:${GITHUB_TOKEN}@github.com/jeetiss/try-release-it.git
        - git fetch
        - git branch -u origin/master
        - git update-index --assume-unchanged .npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm run release -- --ci

stages:
  - name: release
    if: "branch = master AND type = push AND commit_message !~ /(no-release|chore: release)/"
```
