### ISSUE TITLE
Why need to login in CI?

### ISSUE THREAD

**Issue by matteodisabatino** [release-it/release-it#739]
Hi,
I made a module in which I use release-it (via Github Actions) to create release and tag but *not* for publish to npm. Here the code:
```yml
name: CI

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: git config
        run: |
          git config user.email "matteo.di.sabatino.1989@gmail.com"
          git config user.name "Matteo Di Sabatino"
      - run: npm i
      - run: npm test
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## Other jobs down there
```

The job work fine but I cannot understand why I need to run "git config" if there is an access token. Note that "secrets.GITHUB_TOKEN" is a special access token, generated by CI directly, that owns all permission in the repo; if I use an access token of mine (that I called "secrets.AT") there is no change: I always have to make "git config".

I would like to know if this is normal or if I'm missing something. And if this is the correct behaviour, I would like to know if there is a *clean way* that let me avoid specify my personal information (although they are public).

Thanks in advance.
