### ISSUE TITLE
Cannot Publish with Travis CI

### ISSUE THREAD

**Issue by iamyoki** [release-it/release-it#805]
I've tried so many times, never success.

Please view my build history, there are hundreds of times failed.
https://app.travis-ci.com/github/iamyoki/playwright-watch/builds

## Problem 1:
When releasing using yarn, it will fail  with this 
```shell
$ release-it --ci
ERROR Not authenticated with npm. Please `npm login` and try again.
Documentation: https://git.io/release-it-npm
```

## Problem 2:
Always  `ERROR No upstream configured for current branch.` event I've set `npm run release --ci --set-upstream origin main`

```shell
WARNING Unable to verify if user iamyoki is a collaborator for playwright-watch.
ERROR No upstream configured for current branch.
Please set an upstream branch.
Documentation: https://git.io/release-it-git
```

**Comment by webpro** [comment]
What I see in the last is a successful `npm publish`, but a failed `git push` with the error:

> ERROR remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
> remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
> fatal: Authentication failed for 'https://github.com/iamyoki/playwright-watch.git/'

The other command in "problem 2" is incorrect, it should be (also note the extra `--` dashes):

```
npm run release -- --ci --no-git.requireUpstream
```

**Comment by iamyoki** [comment]
Thank you so much, I've tried again, but still error with git.
![image](https://user-images.githubusercontent.com/74389358/132148917-54506a01-63f3-415f-930f-12e7b85535e5.png)

It looks like travis won't allow `git remote set-url` command.

This is my `.release-it.yml` file
```yaml
git:
  commitMessages: "chore: release v${version} [ci skip]"
  pushRepo: "https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/playwright-watch.git"

plugins:
  "@release-it/conventional-changelog":
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: 🚀 Features
        - type: fix
          section: 🧰 Bug Fixes
        - type: chore
          section: 🔫 Chores
        - type: docs
          section: 🌠 Docs
        - type: ci
          section: 🗳️ CICD
        - {}
    infile: CHANGELOG.md

```

**Comment by iamyoki** [comment]
@webpro  Thank you again, I found the key problem, I forgot `git config --global user.name`, that's why it always fail with git.

My successful `.travis.yml`
```yaml
language: node_js

node_js:
  - 14

cache: npm

branches:
  only:
    - main

install:
  - npm ci

script:
  - npm build

after_success: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "yokiyuqian@gmail.com"
  - git remote set-url origin https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/playwright-watch.git
  - git symbolic-ref HEAD refs/heads/main

deploy:
  provider: script
  script: npm run release -- --ci --no-git.requireUpstream
  skip_cleanup: true
  on:
    branch: main

```
