### ISSUE TITLE
GitLab CI ERROR fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by nunof07** [release-it/release-it#834]
Hi,

Thank you for this awesome package 👍 .

I'm trying to setup an automated release from GitLab.

Here is what I'm looking to do:
- When I create a tag in Gitlab
- Trigger a release
- Read the version from the Git tag
- Update package.json with the version
- Update changelog
- Push to Git
- Publish to npm
- Publish GitLab release

However, after trying all sorts of things, I can't get past `ERROR fatal: ref HEAD is not a symbolic ref`.

Here is the release-it config:

```json
{
  "hooks": {
    "before:init": "git fetch --prune --prune-tags origin",
    "after:release": "echo Successfully released ${version} to ${repo.repository}."
  },
  "git": {
    "pushArgs": ["--follow-tags", "-o ci.skip"]
  },
  "npm": {
    "skipChecks": true,
    "ignoreVersion": true
  },
  "gitlab": {
    "release": true
  },
  "plugins": {
    "@release-it/keep-a-changelog": {
      "filename": "CHANGELOG.md"
    }
  }
}
```

And the GitLab script:

```yaml
release:
  stage: release
  image: node:16-alpine
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE !~ /^Release .*/
  before_script:
    - apk add --no-cache git openssh
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git checkout $CI_BUILD_REF_NAME
    - git remote set-url origin "git@gitlab.com:$CI_PROJECT_PATH.git"
    - git pull origin $CI_BUILD_REF_NAME
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm ci
  script:
    - git status
    - DEBUG=release-it:* npx release-it --ci --dry-run --verbose -VV
```

I'm doing a dry-run until I can figure out it's working.

And this is the log:

```
$ git status
HEAD detached at 0d579f5
nothing to commit, working tree clean
$ DEBUG=release-it:* npx release-it --ci --dry-run --verbose -VV
2021-11-18T17:03:21.609Z release-it:config {
  cosmiconfig: {
    config: {
      hooks: [Object],
      git: [Object],
      npm: [Object],
      gitlab: [Object],
      plugins: [Object]
    },
    filepath: '/builds/codersclan/tools/airfleet-generator/.release-it.json'
  }
}
2021-11-18T17:03:21.619Z release-it:config {
  system: { 'release-it': '14.11.7', node: 'v16.13.0', os: 'Linux 4.9' }
}
2021-11-18T17:03:21.621Z release-it:config {
  _: [],
  ci: true,
  'dry-run': true,
  d: true,
  verbose: 3,
  increment: undefined,
  hooks: {
    'before:init': 'git fetch --prune --prune-tags origin',
    'after:release': 'echo Successfully released ${version} to ${repo.repository}.'
  },
  git: {
    pushArgs: [ '--follow-tags', '-o ci.skip' ],
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    requireCleanWorkingDir: true,
    requireBranch: false,
    requireUpstream: true,
    requireCommits: false,
    addUntrackedFiles: false,
    commit: true,
    commitMessage: 'Release ${version}',
    commitArgs: [],
    tag: true,
    tagName: null,
    tagMatch: null,
    tagAnnotation: 'Release ${version}',
    tagArgs: [],
    push: true,
    pushRepo: ''
  },
  npm: {
    skipChecks: true,
    ignoreVersion: true,
    publish: true,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    timeout: 10
  },
  gitlab: {
    release: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    tokenRef: 'GITLAB_TOKEN',
    tokenHeader: 'Private-Token',
    certificateAuthorityFile: null,
    assets: null,
    origin: null,
    skipChecks: false
  },
  plugins: { '@release-it/keep-a-changelog': { filename: 'CHANGELOG.md' } },
  github: {
    release: false,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    preRelease: false,
    draft: false,
    tokenRef: 'GITHUB_TOKEN',
    assets: null,
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false,
    web: false
  },
  version: {
    increment: undefined,
    isPreRelease: false,
    preReleaseId: undefined
  }
}
2021-11-18T17:03:21.641Z release-it:config { 'keep-a-changelog': { filename: 'CHANGELOG.md' } }
2021-11-18T17:03:21.645Z release-it:plugins {
  namespace: 'keep-a-changelog',
  options: { filename: 'CHANGELOG.md' }
}
2021-11-18T17:03:21.684Z release-it:plugins {
  namespace: 'npm',
  options: {
    skipChecks: true,
    ignoreVersion: true,
    publish: true,
    publishPath: '.',
    publishArgs: [],
    tag: null,
    otp: null,
    timeout: 10
  }
}
2021-11-18T17:03:21.687Z release-it:plugins {
  namespace: 'gitlab',
  options: {
    release: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    tokenRef: 'GITLAB_TOKEN',
    tokenHeader: 'Private-Token',
    certificateAuthorityFile: null,
    assets: null,
    origin: null,
    skipChecks: false,
    tagName: null,
    pushRepo: '',
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}'
  }
}
2021-11-18T17:03:21.688Z release-it:plugins {
  namespace: 'version',
  options: {
    increment: undefined,
    isPreRelease: false,
    preReleaseId: undefined
  }
}
2021-11-18T17:03:21.702Z release-it:plugins {
  namespace: 'git',
  options: {
    pushArgs: [ '--follow-tags', '-o ci.skip' ],
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    requireCleanWorkingDir: true,
    requireBranch: false,
    requireUpstream: true,
    requireCommits: false,
    addUntrackedFiles: false,
    commit: true,
    commitMessage: 'Release ${version}',
    commitArgs: [],
    tag: true,
    tagName: null,
    tagMatch: null,
    tagAnnotation: 'Release ${version}',
    tagArgs: [],
    push: true,
    pushRepo: ''
  }
}
! git fetch --prune --prune-tags origin
$ git diff --quiet HEAD
2021-11-18T17:03:21.729Z release-it:shell {
  command: 'git diff --quiet HEAD',
  options: { write: false },
  code: 0,
  stdout: '',
  stderr: ''
}
$ git rev-parse --abbrev-ref HEAD
HEAD
2021-11-18T17:03:21.750Z release-it:metrics {
  url: 'http://www.google-analytics.com/collect',
  statusCode: 200,
  statusMessage: 'OK',
  payload: 'v=1&tid=UA-108828841-1&cid=f1be908a-720b-468c-9961-ff0a68819c49&cd1=14.11.7&cd2=v16.13.0&cd3=Linux+4.9&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=1&cd12=1&cd13=1&cd14=0&cd15=undefined&cd16=1&t=event&ec=session&ea=start'
}
2021-11-18T17:03:21.752Z release-it:shell {
  command: 'git rev-parse --abbrev-ref HEAD',
  options: { write: false },
  code: 0,
  stdout: 'HEAD',
  stderr: ''
}
$ git config --get branch.HEAD.remote
2021-11-18T17:03:21.765Z release-it:shell {
  command: 'git config --get branch.HEAD.remote',
  options: { write: false },
  code: 1,
  stdout: '',
  stderr: ''
}
$ git remote get-url origin
git@gitlab.com:codersclan/tools/airfleet-generator.git
2021-11-18T17:03:21.776Z release-it:shell {
  command: 'git remote get-url origin',
  options: { write: false },
  code: 0,
  stdout: 'git@gitlab.com:codersclan/tools/airfleet-generator.git',
  stderr: ''
}
! git fetch
$ git describe --tags --match=* --abbrev=0
0.1.0
2021-11-18T17:03:21.796Z release-it:shell {
  command: 'git describe --tags --match=* --abbrev=0',
  options: { write: false },
  code: 0,
  stdout: '0.1.0',
  stderr: ''
}
$ git symbolic-ref HEAD
2021-11-18T17:03:21.797Z release-it:config {
  tagTemplate: '${version}',
  latestTag: '0.1.0',
  secondLatestTag: null
}
fatal: ref HEAD is not a symbolic ref
2021-11-18T17:03:21.814Z release-it:shell {
  command: 'git symbolic-ref HEAD',
  options: { write: false },
  code: 128,
  stdout: '',
  stderr: 'fatal: ref HEAD is not a symbolic ref\n'
}
2021-11-18T17:03:21.843Z release-it:metrics {
  url: 'http://www.google-analytics.com/collect',
  statusCode: 200,
  statusMessage: 'OK',
  payload: 't=exception&exd=Error%3A+fatal%3A+ref+HEAD+is+not+a+symbolic+ref'
}
ERROR fatal: ref HEAD is not a symbolic ref
```

Any help would be appreciated. Thank you 🙏
