### ISSUE TITLE
Is posible to use GITLAB_TOKEN instead of ssh key?

### ISSUE THREAD

**Issue by AonzVongsunthorn** [release-it/release-it#913]
Hello,

Currently, I do some PoC about the version management on Gitlap CI with your library.
Then I stuck with some conditions about ssh so I would like to use the personal token instead.

After I spend the time doing the PoC, I cannot find the way to use only  GITLAB_TOKEN setting.

My current config:
```json
{
  "git": {
    "tagName": "${version}",
    "requireCleanWorkingDir": false,
    "requireUpstream": false,
    "commitMessage": "chore(release): v%s"
  },
  "npm": {
    "publish": false
  },
  "gitlab": {
    "tokenHeader": "PRIVATE-TOKEN",
    "release": false
  }
}
```

and my gitlab ci configuration is:
```yml
version_bumping:
  stage: version_bump
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_MESSAGE !~ /^chore\(release\)/'
  before_script:
    - *setup-npmrc-script
    - cd src/function && npm ci --legacy-peer-deps
    - git config --global user.email "ci-bot@xxxxxxx.com"
    - git config --global user.name "ci-bot"
    - git config receive.advertisePushOptions true
    - git config --global http.sslVerify false
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script:
    - git branch --show-current
    - echo $GITLAB_TOKEN
    - npm run release -- minor 
    # - git push https://GITLAB_TOKEN:${GITLAB_TOKEN}@{URL} --follow-tags $CI_COMMIT_BRANCH:$CI_COMMIT_BRANCH
```
If can only build a version and generate the release notes, it's fine because I can commit and push back to my repo with `git push` command.
