### ISSUE TITLE
Using release-it against a protected branch in GitHub Actions

### ISSUE THREAD

**Issue by kylegwalsh** [release-it/release-it#940]
I've been struggling to try and get release-it to run against a protected branch in our GitHub Actions CI pipeline for a while now.

Here is the use case:

- We want to restrict contributors so that they have to open a PR before merging their changes (we allow admins to push directly)
- We want to use release-it to bump the package version / changelog whenever a PR occurs

My issue is that the release-it seems to always try to use the GitHub Actions GITHUB_TOKEN env variable (even if I try to reconfigure git during the CI). This results in the token not being an "admin" and the push being rejected:

```
✖ Git push
ERROR remote: error: GH006: Protected branch update failed for refs/heads/dev.        
remote: error: Changes must be made through a pull request.        
 ! [remote rejected] dev -> dev (protected branch hook declined)
```

Here are some thing that I've tried:
- Granting the merging user "admin" access (I don't think this has an impact since GITHUB_TOKEN is set by the runner)
- Manually overriding GITHUB_TOKEN to be the PAT before release-it runs (not entirely sure why this doesn't work unless GitHub Actions is enforcing the variable doesn't change)

I'd also like to note that release-it works fine locally against the protected branch, so it seems like the issue does stem from the GITHUB_TOKEN that is set by the CI.

Is there any way that I can directly and manually provide a custom PAT to the release-it CLI? Or am I approaching this completely wrong to begin with?

**Comment by webpro** [comment]
The `GITHUB_TOKEN` environment variable (or whichever name is configured) is not used for Git operations. It is used only for GitHub Releases using the Octokit REST client (i.e. when `github.release: true`).

**Comment by kylegwalsh** [comment]
Hi @webpro, thank you for your response. If the GITHUB_TOKEN is not used to push version changes back into git, then what is? That token was the only difference I could discern between the CI process and my local process (which works without issue).

**Comment by webpro** [comment]
Probably SSH

- https://github.com/release-it/release-it/blob/master/docs/git.md#git-remotes
- https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by kylegwalsh** [comment]
@webpro That seems to have worked.

For anyone else who encounters this issue, here is what I did to make things work (all steps might not be necessary, but it worked on the first run and I don't feel like delving any deeper):

1. I started by generating an SSH private / public key via the following command: 

```
ssh-keygen -t ed25519 -a 100 -f path/to/keyfile
```

2. I attached this SSH key to a machine-user that I created in Github and uploaded the private key as a secret to my Github repo (`GIT_SSH_PRIVATE_KEY`)

3. I then modified my Github actions CI file to configure the user, remote, and SSH key

```
      # Configure git in case we need to bump our app versions
      - name: Configure git
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'CI Bot'
          email: 'my-ci-bot@email.com'
          actor: 'my-ci-bot'
          token: '${{ secrets.GIT_TOKEN }}'
      # Change git remote to be SSH so that release-it can get around PR requirement
      - name: Change git remote to use SSH
        run: |
          git remote set-url origin git@github.com:home-lending-pal/hlp-borrower-app.git
      # Configure SSH with hlp-ci-bot's private SSH key
      - name: Attach SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
```

3. And finally I ran release it and the CI process took on the permissions of the SSH key user
