### ISSUE TITLE
Push to protected branch not working

### ISSUE THREAD

**Issue by toondaey** [release-it/release-it#962]
I recently setup a github actions which should automatically publish to npm and push to github. The npm publish seems to be working just fine however, I can't seem to get the push to github working. Here are snippets of my configuration:

`.release-it.json`
```json
{
  "git": {
    "commitMessage": "chore(release): ${version}",
    "tag": false,
    "push": true,
    "pushArgs": ["--follow-tags"],
    "requireBranch": "master"
  },
  "npm": {
    "publish": true,
    "skipChecks": false
  },
  "github": {
    "publish": true,
    "release": true,
    "releaseName": "Release v${version}"
  }
}
```

`publish.yaml`
```yaml
name: deploy to npm

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update npm
        run: sudo npm install -g npm@latest

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Authenticate npm registry
        run: sudo npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: install yarn
        run: sudo npm install -g --force yarn

      - name: install dependencies
        run: yarn

      - name: Publish to npm
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

The `release` script in package.json is this: `dotenv release-it --`

Below is the error I keep getting with every attempt I've made:

```
remote: error: At least 1 approving review is required by reviewers with write access. Commits must have valid signatures. 6 of 6 required status checks are expected.        
To https://github.com/toondaey/nestjs-got
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/toondaey/nestjs-got'
Rolling back changes...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
