### ISSUE TITLE
GitHub Actions: ERROR fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by DawChihLiou** [release-it/release-it#990]
Hi team,

I'm experiencing an error with `release-it` on GitHub Actions. The error `ERROR fatal: ref HEAD is not a symbolic ref` occurred when running `--dry-run` on a feature branch in a private GitHub repository. Please see the screenshot:

<img width="1050" alt="Screenshot 2023-03-20 at 18 11 15" src="https://user-images.githubusercontent.com/4335023/226416901-4d2936f6-9694-4786-b58c-b381984a6a26.png">

The release job is written as following:

```yaml
release:
     runs-on: ubuntu-20.04
     permissions:
       contents: write
       pull-requests: write
     needs: ['prettier', 'lint', 'test']
     steps:
       - uses: actions/checkout@v3

       - uses: actions/setup-node@v3
         with:
           node-version: '16.x'

       - uses: actions/cache@v3
         id: yarn-cache
         with:
           path: node_modules
           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
             ${{ runner.os }}-yarn-
       - name: Config git user
         run: |
           git config --global user.email "$GIT_USER_EMAIL"
           git config --global user.name "$GIT_USER_NAME"
       - name: Dry Run
         if: ${{ github.ref != 'refs/heads/main'}}
         run: yarn release --dry-run

       - name: Release
         if: ${{ github.ref == 'refs/heads/main' }}
         run: yarn release --ci
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It'd be great if you can point me to the right direction to fix the issue. Thanks!
